### ISSUE TITLE
Caesar Cipher issue

### ISSUE THREAD

**Issue by supershdow** [blazer1461/Half-Smart#1]
Cipher returns an internal error when key is 54 or when both key and word are empty

**Comment by UltraxBlade** [comment]
Cipher returns that error with a wide range of numbers, and also doesn't always decipher properly when the result is copied in and used with negative key number.

**Comment by lIIlIIlIIl** [comment]
Thanks for the feedback.

**Comment by blazer1461** [comment]
Its being worked on now with a drop-down menu
